dist: xenial
language: node_js

node_js:
  - '10'

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - npm install
  - ng lint

install:
  - ng build --prod --base-href "https://tenders-recommender.github.io/"

script:
  - pwd
  - npx ngh --repo=https://GH_TOKEN@github.com/tenders-recommender/tenders-recommender.github.io.git
    --branch=master --dir=dist/tenders-recommender

env:
  global:
    secure: nlqEExVv7mb0BQbU6ZkkLRN8qPWZ6BOu5UyMffZCPTClJbEA0C8t4/+OS/jQ8Kn8TZmp4mSjTfIu7ytiKe5VaLSrhn7qAXfFBNtoCbWKeN6bOs6RiIHvmd+ZbuYT9xzxvDU21OctTFFsi7q8CKnkAyQKEc9yAGMOkU3Pg6hTjl+7NXe8xCFW/2QwUawrOAEb+erKi2d/ipnq6oqfUzTD/H3uDoaGocwyAx797hZoeCM7AP+CNV/k+W8W07OrQXBLDCZ1OxiGMDyztmZ+Q2Yw7E2sQfUx8yKVLBjrYU9MiL1AdDR97kpq5Ksvd8V02mzInNpIt7A4YIQ+jOE9oQiKkvzAOk+ZMMS4UXKJ2E+TrQc6ZlUFtYpDODhnfU36jAkZrOyBcZs3Mocpf6WjeM2EHviENVYw0usMFowxsWD6qx2sr0KL8ra+98eJzgI2gQsHprxyjrt2yweD0fFZRNNoPpAAu1F3lyg6ksh51fItylR2AZ7U9GNKI9VaPCUsrusagxADHmWeq84tjmKbdMTCS7eENrSwrysNUFEckmi00J+ypTmwhql82tiJgWwRPxkSF2v6jnW3GoDhrn8SplojBYK5m9yJRvdnbAVUKiShhJYFDR6WIqPRcwDTQY5zbof1AGJQuQpGWZJqAScNO1HI7AjOe897iIkg8Gbh745P7kU=
